language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - add-on
    - extra

  licenses:
    - 'android-sdk-license-.+'

  notifications:
    email: false

before_install:
    - yes | /usr/local/android-sdk/tools/bin/sdkmanager --licenses

script:
  - ./gradlew build connectedCheck --info
