language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - android-27

  licenses:
    - 'android-sdk-license-.+'
    - '.+'

  notifications:
    email: false

before_install:


before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew build connectedCheck --info
