language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - add-on
    - extra

  licenses:
    - 'android-sdk-license-.+'

  notifications:
    email: false

before_install:
    - yes | sdkmanager --licenses

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - chmod +x ./gradlew
  - ./gradlew build connectedCheck --info
