language: android
android:
env:
  global:
    - COMPILE_SDK_VERSION = 25
    - BUILD_TOOLS_VERSION = 25.0.2
  components:
    - platform-tools
    - tools
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$COMPILE_SDK_VERSION

  notifications:
    email: false