language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.1
    - android-27

  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'

  notifications:
    email: false

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew build connectedCheck --info
